### ISSUE TITLE
HMac-SHA3-512 签名算法无法使用

### ISSUE THREAD

**Issue by houzepeng** [opay-services/opay-sdk-java#1]
你好，回掉接口需要用HMac-SHA3-512，这个util下的HMac-SHA3-512无法使用，报空指针，你那边可以使用吗？

**Comment by Anwj** [comment]
不要直接调用HmacUtils的方法，用SignatureUtils类，SignatureUtils.verifyTransactionSignature()是收单交易状态的验签，SignatureUtils.verifyTopupSignature()是博彩和话费充值交易状态的验签。
